# Generated by Django 5.0 on 2023-12-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tc',
            field=models.BooleanField(default=False),
        ),
    ]
